"""Multimodal utilities — image generation (DALL-E / SVG placeholder) and TTS (OpenAI / browser)."""
import json
import logging
import base64
import os
from pathlib import Path
from src.agents.base import get_mode
from src.config import OPENAI_API_KEY, GENERATED_DIR

logger = logging.getLogger(__name__)


# ════════════════════════════════════════════════════════════════
# IMAGE GENERATION
# ════════════════════════════════════════════════════════════════

def generate_concept_image(topic: str, module_title: str, description: str = "") -> dict:
    """
    Generate a concept diagram/illustration for a lesson.
    Returns: {type: "url"|"svg"|"placeholder", data: str, prompt: str}
    """
    mode = get_mode()
    prompt = f"A clean, educational diagram illustrating the concept of '{module_title}' in {topic}. Simple, professional, minimal text, white background, suitable for a textbook."

    if mode == "api" and OPENAI_API_KEY:
        return _dalle_generate(prompt)
    else:
        return _svg_placeholder(topic, module_title)


def _dalle_generate(prompt: str) -> dict:
    """Generate image via DALL-E 3 API."""
    try:
        from openai import OpenAI
        client = OpenAI(api_key=OPENAI_API_KEY)
        response = client.images.generate(
            model="dall-e-3",
            prompt=prompt,
            size="1024x1024",
            quality="standard",
            n=1,
        )
        url = response.data[0].url
        return {"type": "url", "data": url, "prompt": prompt}
    except Exception as e:
        logger.warning(f"DALL-E generation failed: {e}")
        return _svg_placeholder("Topic", "Concept")


def _svg_placeholder(topic: str, module_title: str) -> dict:
    """Generate an SVG placeholder diagram."""
    # Create a visually appealing SVG concept diagram
    colors = ["#667eea", "#764ba2", "#f093fb", "#4facfe", "#00f2fe",
              "#43e97b", "#fa709a", "#fee140", "#30cfd0", "#a8edea"]

    import hashlib
    color_idx = int(hashlib.md5(module_title.encode()).hexdigest()[:2], 16) % len(colors)
    c1, c2 = colors[color_idx], colors[(color_idx + 3) % len(colors)]

    # Extract key terms for the diagram
    terms = module_title.split()[:4]
    if len(terms) < 2:
        terms = [topic] + terms

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 300">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:{c1};stop-opacity:0.15"/>
      <stop offset="100%" style="stop-color:{c2};stop-opacity:0.15"/>
    </linearGradient>
    <linearGradient id="accent" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:{c1}"/>
      <stop offset="100%" style="stop-color:{c2}"/>
    </linearGradient>
  </defs>
  <rect width="600" height="300" rx="16" fill="url(#bg)" stroke="{c1}" stroke-width="2"/>
  <text x="300" y="40" text-anchor="middle" font-family="Arial,sans-serif" font-size="16" fill="{c1}" font-weight="bold">📚 {topic}</text>
  <rect x="150" y="60" width="300" height="50" rx="25" fill="url(#accent)" opacity="0.9"/>
  <text x="300" y="90" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" fill="white" font-weight="bold">{module_title[:30]}</text>
  <line x1="300" y1="110" x2="300" y2="140" stroke="{c1}" stroke-width="2"/>
  <line x1="300" y1="140" x2="150" y2="170" stroke="{c1}" stroke-width="2"/>
  <line x1="300" y1="140" x2="300" y2="170" stroke="{c1}" stroke-width="2"/>
  <line x1="300" y1="140" x2="450" y2="170" stroke="{c1}" stroke-width="2"/>'''

    # Add concept bubbles
    positions = [(150, 195), (300, 195), (450, 195)]
    labels = (terms + ["Concepts", "Practice", "Mastery"])[:3]
    for (x, y), label in zip(positions, labels):
        svg += f'''
  <rect x="{x-55}" y="{y-25}" width="110" height="40" rx="20" fill="white" stroke="{c1}" stroke-width="1.5"/>
  <text x="{x}" y="{y+5}" text-anchor="middle" font-family="Arial,sans-serif" font-size="13" fill="{c1}">{label[:14]}</text>'''

    svg += f'''
  <text x="300" y="275" text-anchor="middle" font-family="Arial,sans-serif" font-size="11" fill="#888">Generated by LearnForge — Concept Diagram</text>
</svg>'''

    return {"type": "svg", "data": svg, "prompt": f"Concept diagram for {module_title} in {topic}"}


# ════════════════════════════════════════════════════════════════
# TEXT-TO-SPEECH
# ════════════════════════════════════════════════════════════════

def generate_audio(text: str, voice: str = "alloy") -> dict:
    """
    Convert text to speech.
    Returns: {type: "audio_bytes"|"browser_tts", data: bytes|str, format: "mp3"|"browser"}
    """
    mode = get_mode()

    if mode == "api" and OPENAI_API_KEY:
        return _openai_tts(text, voice)
    else:
        # Return text for browser-native TTS (handled in Streamlit frontend)
        return {"type": "browser_tts", "data": text, "format": "browser"}


def _openai_tts(text: str, voice: str = "alloy") -> dict:
    """Generate audio via OpenAI TTS API."""
    try:
        from openai import OpenAI
        client = OpenAI(api_key=OPENAI_API_KEY)

        # Truncate to ~4000 chars (API limit is 4096)
        text = text[:4000]

        response = client.audio.speech.create(
            model="tts-1",
            voice=voice,
            input=text,
        )

        audio_bytes = response.content

        # Also save to file
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        from datetime import datetime
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        audio_path = GENERATED_DIR / f"audio_{ts}.mp3"
        with open(audio_path, "wb") as f:
            f.write(audio_bytes)

        return {"type": "audio_bytes", "data": audio_bytes, "format": "mp3", "path": str(audio_path)}
    except Exception as e:
        logger.warning(f"OpenAI TTS failed: {e}")
        return {"type": "browser_tts", "data": text, "format": "browser"}


def get_tts_voices():
    """Available OpenAI TTS voices."""
    return ["alloy", "echo", "fable", "onyx", "nova", "shimmer"]
